Rewritten TeamSpec::balance_extents() to balance more than two dimensions
dash-project/dash pull request #229
Opened 2017-01-04 01:47 UTC by ddiefenthaler

I've rewritten balance_extents to use a different algorithm.

2017-01-04 02:58 UTC, ddiefenthaler commented
The idea behind the algorithm is to equally distribute the prime factors across the dimensions as good as possible. Starting with the largest factors they get multiplied with `this->extents[i]` with `i` growing.
As long as there are enough remaining prime factors this condition should be true:
`this->_extents[0] >= this->_extents[1] >= ... >= this->_extents[MaxDimensions-1]`
If the last iteration over `this->_extents` is incomplete the direction gets reversed to even the effect out. (Starting with `this->_extents[MaxDimensions-1]` downwards)

Thinking about it, it may make sense to change the direction each iteration over `this->_extents`,
but I'm not sure about this... I can't see what would happen after the second iteration.

2017-01-04 06:44 UTC, fuchsto requested changes
Thank you, but please implement additional unit tests to cover the new functionality.

2017-01-04 06:45 UTC, fuchsto commented
Addresses #228

2017-01-06 17:24 UTC, ddiefenthaler commented
I added a unit test,
but I think that the algorithm should still be changed once more.
I assume that my approach only works well if the number of units factorizes in not to many different factors.
Apart from that the algorithm does not consider any constraints.
@fuchsto It would be nice if you could clarify how balance_extents should behave.

2017-02-08 10:20 UTC, ddiefenthaler commented
I added another commit, I think this is in a mergable state now.

I am sure there are more optimizations possible, but for now this works too.

I removed the adjustment of `_is_linear`, that led to `MatrixTest.CopyRow` failing,
but I think this is another error so I will open a seperate issue for that.

2017-02-08 21:00 UTC, ddiefenthaler commented
I think this Pull request is fine now,
@fuchsto can you review this again?

2017-02-12 18:55 UTC, fmoessbauer commented on dash/include/dash/TeamSpec.h
> +        new_extents.insert(it->first * *new_extents.begin());
You are not a fan of brackets, are you? ;)

2017-02-13 12:00 UTC, fuchsto approved these changes

2017-02-13 12:01 UTC, fuchsto commented
@ddiefenthaler Looking good!

2017-02-13 12:16 UTC, fuchsto commented
@ddiefenthaler I don't care too much about efficiency of this implementation for now. Integer factorization is NP-hard, anyways.
This function is supposed to be called once for a reasonably large unit of work, as in domain decomposition of a 2048x2048 matrix-matrix multiplication. Even if it was inefficient, it would not notably affect the overall time to completion.

2017-02-13 12:21 UTC, merged