Feat 231 ccwarn
dash-project/dash pull request #232
Opened 2017-01-06 08:27 UTC by fuchsto

2017-01-06 09:03 UTC, fmoessbauer requested changes
The compiler flag changes look good to me, but then we also should fix all the warnings. Currently my compiler (gcc5) generates a massive amount of warnings.

Request changes: see my comment on `dash::myid()`

2017-01-06 09:03 UTC, fmoessbauer commented on dash/include/dash/internal/Logging.h
That cannot be removed, as logging is used in Team.cc and vise versa.
Error (gcc5):
```bash
In file included from /opt/dash/dash/include/dash/util/Timer.h:20:0,                                  │ 1 file changed, 4 insertions(+)
                 from /opt/dash/dash/src/util/TimestampClockPosix.cc:1:                               │ felix@HIGHPOWER  ~/repos/github-dash/dash   feat-hdf5-views ●  git commit -a
/opt/dash/dash/include/dash/internal/Logging.h: In function 'void dash::internal::logging::Log_Line(co│[feat-hdf5-views aaa90a2] skip ASIO test if using mpich, as ASIO unrelated concurrency problems occure
nst char*, const char*, int, const char*, const string&)':                                            │ 1 file changed, 10 insertions(+), 2 deletions(-)
/opt/dash/dash/include/dash/internal/Logging.h:194:29: error: 'myid' is not a member of 'dash'        │ felix@HIGHPOWER  ~/repos/github-dash/dash   feat-hdf5-views  git push
   dash::global_unit_t uid = dash::myid();
```

2017-01-08 19:44 UTC, fuchsto commented on dash/include/dash/internal/Logging.h
Right, re-added the forward-declaration.

2017-01-08 19:47 UTC, fuchsto commented
@fmoessbauer The "excessive" compiler warnings are only enabled in developer (not debug) build config, so we don't have to fix all of them right now. There just should be a way to make them visible.

2017-01-08 20:49 UTC, fmoessbauer approved these changes

2017-01-09 07:49 UTC, merged