Feat 249 atomic
dash-project/dash pull request #255
Opened 2017-01-26 10:02 UTC by fmoessbauer

Make `dash::Atomic` trivially copyable

2017-01-27 00:28 UTC, fuchsto requested changes
@dash-project/developers Do not use wrapper functions for atomic operations that hide the atomic type!

See my comment here:

https://github.com/dash-project/dash/issues/249#issuecomment-275514703

2017-01-28 13:25 UTC, fmoessbauer commented
As discussed yesterday, I finally managed to change the interface in a way that follows as close as possible the C++11 standard as well as `std::atomic`.

This introduces the following changes:
- old `dash::Atomic` becomes `dash::AtomicAddress`
- new version of `dash::Atomic` is phantom type
- provide algorithms to change `GlobRef<Atomic<>>`
- specialize `GlobRef<Atomic>` to provide atomic interface
- name atomic interface according to std::atomic

Please review it very carefully.

2017-01-30 07:58 UTC, devreal requested changes
Great work! Some suggestions for improvements inline. I will take care of implementing `dart_compare_and_swap` today.

2017-01-30 07:58 UTC, devreal commented on dash/include/dash/Atomic.h
> +    dart_flush_all(_gptr);
Two things: 

1. Is the flush really required? The assignment should use `dart_put_blocking`, which issues a flush at the end. 
2. More importantly: This operation is not atomic and might thus conflict with other atomic operations executed on this memory. I suggest using `dart_accumulate`, which is guaranteed to be atomic (implemented in terms of `MPI_Accumulate`.

2017-01-30 07:58 UTC, devreal commented on dash/include/dash/Atomic.h
>      reference ref(_gptr);
See my comment on `set()`. Better use `dart_fetch_and_op` with `DART_OP_NONE`. Alternatively, we might consider implementing a counterpart of `MPI_Get_accumulate`, i.e., `dart_get_accumulate`.

2017-01-30 07:58 UTC, devreal commented on dash/include/dash/Atomic.h
> +    // TODO;
I guess this requires something like `dart_compare_and_swap()`, will add an implementation of it today.

2017-01-30 07:58 UTC, devreal commented on dash/include/dash/GlobRef.h
> +
grrr, why all those trailing whitespaces?

2017-01-30 07:58 UTC, devreal commented on dash/include/dash/GlobRef.h
> +
I suggest moving this specialization to `Atomic.h` as non-atomic use does not require it to compile successfully.

2017-01-30 18:30 UTC, fmoessbauer commented
@devreal Thanks for your comments. I did some major restructuring of the atomic types / classes and algorithms. Now the interface is clean and can be loaded by including `dash/Atomic.h`.

And now to the technical part: I changed the implementation according to your comments, but unfortunately now the atomics do not work anymore. For me it seems that the dart versions of MPI accumulate functions lose some of the atomicity guarantees. So please have a look at the changes. In the meantime we could use commit 347cbdb which works perfectly.

2017-01-30 19:33 UTC, fuchsto commented
@fmoessbauer: Good, please wait for my review before further implementation.

2017-01-31 08:39 UTC, devreal commented
@fmoessbauer Thanks for restructuring the code, much better now. You mean that it does not work because of the Segfault? I'm not sure whether this is related to `dart_fetch_and_op`, as the segfault happens in in a flush:

```
#0  0x00007ffff5d64428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff5d6602a in __GI_abort () at abort.c:89
#2  0x00007ffff5da67ea in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7ffff5ebd8a2 "*** %s ***: %s terminated\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff5e4756c in __GI___fortify_fail (msg=<optimized out>, msg@entry=0x7ffff5ebd884 "stack smashing detected") at fortify_fail.c:37
#4  0x00007ffff5e47510 in __stack_chk_fail () at stack_chk_fail.c:28
#5  0x00007ffff08721ac in ?? () from /usr/lib/openmpi/lib/openmpi/mca_btl_vader.so
#6  0x00007ffff50091ea in opal_progress () from /usr/lib/libopen-pal.so.13
#7  0x00007fffeaf70895 in ?? () from /usr/lib/openmpi/lib/openmpi/mca_osc_pt2pt.so
#8  0x00007fffeaf71667 in ompi_osc_pt2pt_flush_all () from /usr/lib/openmpi/lib/openmpi/mca_osc_pt2pt.so
#9  0x00007ffff6d7cf04 in PMPI_Win_flush_all () from /usr/lib/libmpi.so.12
#10 0x000000000071fca8 in dart_flush_all (gptr=...) at /home/joseph/src/dash/dash/dart-impl/mpi/src/dart_communication.c:1108
#11 0x0000000000606bad in dash::GlobMem<dash::Atomic<int>, dash::allocator::CollectiveAllocator<dash::Atomic<int> > >::flush_all (this=<optimized out>)
    at /home/joseph/src/dash/dash/dash/include/dash/GlobMem.h:420
#12 dash::Array<dash::Atomic<int>, long, dash::BlockPattern<1, (dash::MemArrange)1, long> >::barrier (this=0x7fffffffd160, this=0x7fffffffd160)
    at /home/joseph/src/dash/dash/dash/include/dash/Array.h:1082
#13 dash::Array<dash::Atomic<int>, long, dash::BlockPattern<1, (dash::MemArrange)1, long> >::deallocate (this=this@entry=0x7fffffffd160)
    at /home/joseph/src/dash/dash/dash/include/dash/Array.h:1174
#14 0x0000000000600dae in dash::Array<dash::Atomic<int>, long, dash::BlockPattern<1, (dash::MemArrange)1, long> >::~Array (this=0x7fffffffd160, 
    __in_chrg=<optimized out>) at /home/joseph/src/dash/dash/dash/include/dash/Array.h:819
#15 AtomicTest_AtomicInterface_Test::TestBody (this=<optimized out>) at /home/joseph/src/dash/dash/dash/test/AtomicTest.cc:205
#16 0x00000000006e80eb in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*)
    ()
#17 0x00000000006e16ef in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ()
#18 0x00000000006c4e2c in testing::Test::Run() ()
#19 0x00000000006c57c4 in testing::TestInfo::Run() ()
#20 0x00000000006c5eb7 in testing::TestCase::Run() ()
#21 0x00000000006ccffe in testing::internal::UnitTestImpl::RunAllTests() ()
#22 0x00000000006e96c3 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) ()
#23 0x00000000006e2531 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) ()
#24 0x00000000006cba9a in testing::UnitTest::Run() ()
#25 0x00000000004d8a92 in RUN_ALL_TESTS () at /home/joseph/src/dash/dash/build/gtest/src/GTestExternal/googletest/include/gtest/gtest.h:2233
#26 main (argc=1, argv=0x7fffffffd938) at /home/joseph/src/dash/dash/dash/test/main.cc:70
```

Is that the Segfault you see as well? This error appeared using OpenMPI 1.10.2. I will test other versions and MPICH as well.

2017-01-31 12:38 UTC, devreal commented
It seems that the `fetch_and_op` operation corrupts the stack in some way in the test suite. However, I am not able to reproduce this with a small example so it's painful to debug. I'll keep digging through it...

2017-02-01 12:52 UTC, fmoessbauer commented
@devreal Thanks for putting time into this. Yesterday I talked to @rkowalewski and @fuchsto about the flushes. We need them, as we have to ensure remote completion. However I guess they are not necessary for pure read operations?

2017-02-01 13:27 UTC, devreal commented
That's what I realized today, I was assuming that atomic operations are performed on the spot. I guess I was too puzzled by the random errors the missing flushes caused, all MPI implementations are terrible in these cases. Inside `get()`, a call to `dart_flush_local` should be sufficient. Not sure whether that makes any difference though.

2017-02-09 22:50 UTC, fuchsto approved these changes

2017-02-09 23:06 UTC, fuchsto requested changes
The memory model traits are still missing, but I wouldn't care for now. The changes definitely are an improvement compared to the current implementation in `development`.

The memory model concept will be addressed in a separate issue.

2017-02-09 23:06 UTC, fuchsto commented on dash/include/dash/atomic/AtomicAddress.h
> +class AtomicAddress
For consistency, this class template should be named `GlobAtomicRef`. It acts as extension of `GlobRef` by atomic operations, like `GlobAsyncRef` does for async operations.
Leading to my second point: This type should satisfy (and extend) the `GlobRef` concept. I think it already does, but it should be checked and documented.

The name `AtomicAddress` is misleading / incorrect in any case:
An address is not atomic, it's just a (compound) number.
That also is to say: the template class does not provide operations on an **address**, and this would be nonsensical. So let's not use this term here.

Let me illustrate in simplified pseudo code:

```c++
Address a(something);
Address b = a.sub(3); // <-- looks like pointer arithmetic?
```

2017-02-13 10:17 UTC, fuchsto requested changes

2017-02-13 10:17 UTC, fuchsto commented on dash/include/dash/atomic/GlobAtomicRef.h
> +         "dash::AtomicAddress only valid on integral and floating point types");
Should be `dash::GlobRef<dash::Atomic<T>>` in static assertion message

2017-02-13 10:17 UTC, fuchsto commented on dash/include/dash/atomic/GlobAtomicRef.h
> +    DASH_LOG_DEBUG_VAR("AtomicAddress.set()", value);
Log messages have scope "AtomicAddress"

2017-02-13 17:00 UTC, fuchsto approved these changes

2017-02-13 17:02 UTC, fuchsto commented
@fmoessbauer Are all comments by @devreal addressed in your recent changes?

2017-02-13 17:04 UTC, devreal approved these changes

2017-02-13 18:51 UTC, merged