fixed ambiguous ctor of BlockPattern
dash-project/dash pull request #304
Opened 2017-02-28 22:19 UTC by fmoessbauer

removed ambiguous constructors in BlockPattern and BlockPattern1D

2017-02-28 22:24 UTC, fuchsto requested changes
The issue is not about an "ambiguous constructor" in BlockPattern, it's a missing `explicit` in the constructor of `TeamSpec`.

Both constructor variants for BlockPattern are required:

~~~c++
// A:
BlockPattern(sizespec, distspec, team = ALL);
// B:
BlockPattern(sizespec, distspec, teamspec, team = ALL);
~~~

Now, the constructor `TeamSpec(Team)` is not marked explicit. That's why a call of c'tor overload A matches B:

~~~c++
BlockPattern(sizespec, distspec, team)
// -> implicit conversion team -> teamspec and last param has default value:
BlockPattern(sizespec, distspec, TeamSpec(team), team = ALL)
~~~

See c'tors here:

- <https://github.com/dash-project/dash/blob/development/dash/include/dash/TeamSpec.h#L49>
- <https://github.com/dash-project/dash/blob/development/dash/include/dash/TeamSpec.h#L142>
- <https://github.com/dash-project/dash/blob/development/dash/include/dash/TeamSpec.h#L212>

2017-02-28 22:28 UTC, fmoessbauer commented
But the Ctors are ambiguous anyway, as both provide defaults for all except the first parameter. If it's not necessary we can close this PR. I just noticed the problem while trying to instantiate a BlockPattern using just SizeSpec and there, clang reported ambiguous ctor.

2017-02-28 22:32 UTC, fuchsto commented
Nonono, the PR itself is fine.
I overlooked that both c'tors have a common ... param-list-prefix.
Still, the missing explicits are bugging me way more.

2017-03-01 07:29 UTC, fmoessbauer commented
Unfortunately this conversion is already used, so adding `explicit` will generate a chain of other fixes:

```c++
/opt/dash/dash/include/dash/Array.h:790:5: error: no matching constructor for initialization of 'dash::BlockPattern<1, dash::MemArrange::ROW_MAJOR, long>'
    m_pattern(
    ^
/opt/dash/dash/include/dash/Array.h:809:5: note: in instantiation of member function 'dash::Array<int, long, dash::BlockPattern<1, dash::MemArrange::ROW_MAJOR, long> >::Array' requested here
  : Array(nelem, dash::BLOCKED, team)
    ^
/opt/dash/dash/examples/ex.09.view-1dim/main.cpp:40:11: note: in instantiation of member function 'dash::Array<int, long, dash::BlockPattern<1, dash::MemArrange::ROW_MAJOR, long> >::Array' requested here
  Array_t array(nunits * block_size);
          ^
/opt/dash/dash/include/dash/pattern/BlockPattern1D.h:159:13: note: candidate constructor [with Args = <const dash::DistributionSpec<1> &, dash::Team &>] not viable: no known conversion from 'SizeSpec_t'
      (aka 'SizeSpec<1, unsigned long>') to 'SizeType' (aka 'unsigned long') for 1st argument
  constexpr BlockPattern(
            ^
/opt/dash/dash/include/dash/pattern/BlockPattern1D.h:221:3: note: candidate constructor not viable: no known conversion from 'dash::Team' to 'const TeamSpec_t' (aka 'const TeamSpec<NumDimensions, long>')
      for 3rd argument
  BlockPattern(
```

2017-03-01 11:05 UTC, fuchsto commented
Hm, we just could not provide a default for the `team` parameter in the extended constructor?

2017-03-01 14:55 UTC, fmoessbauer commented
But if we leave both constructors they are ambiguous even if we remove the default of the second parameter. Anyway, by prohibiting the conversion, the current dash code will not work anymore.

2017-03-01 18:33 UTC, fuchsto commented
Sorry, I just remembered that I defined these constructors for implicit conversion intentionally to support use cases exactly like these.
A conversion from `Team` to `TeamSpec` is always valid. With the implicit conversion, functions with `TeamSpec` a parameter are more flexible in invocation as it can be specified explicitly or initialized from  a team.

2017-03-01 18:55 UTC, devreal commented
> Sorry, I just remembered that I defined these constructors for implicit conversion intentionally to support use cases exactly like these.

We should document this deliberate choice. 

It seems counter-intuitive having to pass a `TeamSpec` and a `Team` to a function, esp. if it allows me to pass different teams. Why not have the `TeamSpec` expose the Team used to create it and draw the `Team` from there?

2017-03-01 19:16 UTC, fuchsto commented
No, I added a specific c'tor in TeamSpec for this case:
https://github.com/dash-project/dash/blob/development/dash/include/dash/pattern/BlockPattern.h#L261

2017-03-01 19:25 UTC, devreal commented
So I still can do the following: 
```
auto pattern = BlockPattern(
                 SizeSpec(), 
                 DistributionSpec(), 
                 TeamSpec(some_distribution, Team::All().split(2)));
```
And the team in the `TeamSpec` of BlockPattern will be overriden by dash::Team::All? That sounds like it's made to be confusing...

2017-03-01 19:39 UTC, fuchsto commented
Yes, that's the use case I meant in my comment. It's just not a robust interface like that.

2017-03-01 20:02 UTC, fuchsto commented
No, that's fine:

https://github.com/dash-project/dash/blob/development/dash/include/dash/pattern/BlockPattern.h#L261

2017-03-01 20:09 UTC, devreal commented
You end up with extents computed for the split team (they are taken from the passed `TeamSpec` in the `TeamSpec` copy-ctor) and the unit ID from `Team::All()`. Is that valid? Are the extents completely overriden in the copy-ctor? What role does the team play that is passed to `TeamSpec` then?

2017-03-01 20:38 UTC, fuchsto commented
That's what is *passed* to the constructor, but the TeamSpec member in BlockPattern is initialized with both: The Team and the TeamSpec.
Have a look at the initializer list at the code location I linked,

2017-03-01 21:58 UTC, devreal commented
OK, so I traced it down and I see that the initial extents in `TeamSpec` are overridden by the team specified in the copy ctor (which is the defaulted `Team::All`). I stand my ground on the claim that the fact that a posterior defaulted argument overrides the team passed to an earlier argument of the `BlockPattern` ctor is not intuitive. I understand that the `TeamSpec` should not contain the team but hey, I announced the intended team already (in the `TeamSpec`) so why bother announcing it again? This inconsistency should be fixed.

2017-03-01 22:21 UTC, fuchsto commented
Which copy constructor do you mean?
The extents specified by the caller are not overridden. BlockPattern ends up here:

<https://github.com/dash-project/dash/blob/development/dash/include/dash/TeamSpec.h#L104>

But perhaps we are talking about different cases?

About the repeated specification of the team:
Well, you *may* have specified the team already, but TeamSpec can be initialized without specifying a team as well. 
In initialization of TeamSpec with a team, only numeric the attributes (size and gaps mostly) of the team are considered.
TeamSpec is not about "wrapping a team with specs" but "providing hints for topological arrangement of an aribtrary team":

~~~c++
Pattern(
  sizespec,
  distspec,
  TeamSpec<2>(34,45),   // <-- "use this as a hint on how to arrange
  team);                // <--  this team, if possible; otherwise rebalance
                        // or make it work somehow"
~~~

I'm definitely not satisfied with the interface as it is, but I ... inherited 🧀  use cases that had to be supported.

2017-03-13 15:52 UTC, fmoessbauer commented
Can we merge this PR or is there still something to discuss and / or to be changed?

2017-03-13 18:24 UTC, fuchsto requested changes

2017-03-13 18:24 UTC, fuchsto commented on dash/include/dash/pattern/BlockPattern.h
> +    const TeamSpec_t         & teamspec = typename TeamSpec_t::TeamSpec(),
`typename` is wrong here, remove it

2017-03-13 18:24 UTC, fuchsto commented on dash/include/dash/pattern/BlockPattern1D.h
> +    const TeamSpec_t         teamspec = typename TeamSpec_t::TeamSpec(),
same here, `typename` is wrong

2017-03-16 03:47 UTC, fuchsto approved these changes

2017-03-16 04:27 UTC, merged