[WIP] Finish Global Dynamic Memory and Allocator Concepts
dash-project/dash pull request #310
Opened 2017-03-02 02:00 UTC by fuchsto

2017-03-18 19:56 UTC, fuchsto commented
@rkowalewski In the current state of the implementation of scoped allocators, the principle of how local allocation is delegated presumably works, but there is no concept of affine address space sizes.
For example, containers require `MemorySpace:;lbegin / lend` and `MemorySpace::local_size(unit)` as in the `GlobDynamicMem` concept in development branch.
As this is related to global heaps / epoch memory spaces etc. anyways, I will push my proposal to PR #333

2017-04-01 15:20 UTC, devreal requested changes
Since I am on my way to the airport, I don't have time to fully grasp all the details. Comments inline, good otherwise :+1:

2017-04-01 15:20 UTC, devreal commented on dart-if/include/dash/dart/if/dart_globmem.h
> +#endif
I'm not happy with having additional C++ code in DART. Maybe implement these operators somewhere in DASH, potentially in a header wrapping `dart_globmem.h `.

2017-04-01 15:20 UTC, devreal commented on dash/include/dash/allocator/internal/Types.h
> +  memory_block(memory_block &&x) noexcept { *this = std::move(x); }
Shouldn't this `.reset()` `x`?

2017-04-01 15:20 UTC, devreal commented on dash/include/dash/map/UnorderedMap.h
> +    Timer::timestamp_t ts_enter = Timer::Now(), ts_insert, ts_find, d_insert, d_find;
The timestamps are only needed for debugging. They should not be used in builds without debug output.

2017-04-01 15:20 UTC, devreal commented on dash/include/dash/map/UnorderedMap.h
> +    */
Is this still an issue?

2017-04-01 15:20 UTC, devreal commented on dash/include/dash/memory/GlobHeapMem.h
> +                  std::end(_num_attach_buckets),
Iterating over `num_unattached_buckets` may be more efficient.

2017-04-01 15:20 UTC, devreal commented on dash/include/dash/memory/MemorySpace.h
> + * is available. This would therefore harm stability and performance.
Note: the type argument in DART allocation functions is not used and you can safely pass `DART_TYPE_BYTE` to them. It do not affect alignment, which will be taken care of later (DART memory allocation overhaul). In fact, passing the type to the underlying MPI implementation only affects the indexing in access functions (which is in bytes for us, for reasons).

2017-04-01 15:20 UTC, devreal commented on dash/test/allocator/EpochSynchronizedAllocatorTest.cc
> +}
Missing newline.

2017-04-01 15:20 UTC, devreal commented on dash/test/allocator/EpochSynchronizedAllocatorTest.h
> +#endif
No newline.

2017-04-01 15:20 UTC, devreal commented on dash/test/memory/SimpleMemoryPoolTest.h
> + */
That comment seems strange ;)

2017-04-01 19:58 UTC, rkowalewski commented on dash/include/dash/map/UnorderedMap.h
> +    */
no it is not. will remote these comments. :)

2017-04-01 19:59 UTC, rkowalewski commented on dash/include/dash/map/UnorderedMap.h
> +    Timer::timestamp_t ts_enter = Timer::Now(), ts_insert, ts_find, d_insert, d_find;
This was actually a commit by accident. Will remove this either. It is something which does not really belong to this pull request.

2017-04-01 23:31 UTC, fuchsto commented on dash/include/dash/map/UnorderedMap.h
> +      ts_insert = Timer::Now();
Benchmarking / debugging leftovers? If these changes are intended to improve performance, add a benchmark example.

2017-04-06 14:32 UTC, fmoessbauer commented
While implementing this, please also fix the `GlobRef<T>.member()` accessor. This is broken due to the recent changes in `GlobPtr`. I will make an issue for this after I am back again.

2017-05-09 19:02 UTC, fmoessbauer commented on dash/include/dash/allocator/internal/Types.h
> +  memory_block(memory_block &&x) noexcept { *this = std::move(x); }
This looks quite strange. If this works, better use `memory_block(memory_block &&) = default;`

2017-05-09 19:03 UTC, fmoessbauer commented on dash/include/dash/allocator/internal/Types.h
> +  void *ptr;
should be encapsulated in `std::unique_ptr`, as otherwise the ptr is not set to `nullptr` on default move.

2018-11-08 15:37 UTC, merged