Make dart_lock thread-safe
dash-project/dash pull request #331
Opened 2017-03-16 22:17 UTC by devreal

Major cleanups in `dart_synchronization.c` and added thread-safety. Also a few minor fixes.

Fixes #330.

2017-03-17 22:12 UTC, fuchsto requested changes

2017-03-17 22:12 UTC, fuchsto commented on dart-impl/base/include/dash/dart/base/mutex.h
> +  return DART_ERR_INVAL;
Add a log error message here

2017-03-17 22:12 UTC, fuchsto commented on dart-impl/mpi/src/dart_synchronization.c
> +    return DART_ERR_OTHER;
Should return error code from `dart_team_memalloc_aligned`

2017-03-17 22:12 UTC, fuchsto commented on dart-impl/mpi/src/dart_synchronization.c
> +    dart__base__mutex_unlock(&lock->mutex);
All return values unchecked

2017-03-17 22:12 UTC, fuchsto commented on dart-impl/mpi/src/dart_synchronization.c
> +    dart__base__mutex_unlock(&lock->mutex);
Return value unchecked

2017-03-17 22:12 UTC, fuchsto commented on dart-impl/mpi/src/dart_synchronization.c
> +    dart__base__mutex_unlock(&lock->mutex);
Return value unchecked

2017-03-17 22:12 UTC, fuchsto commented on dart-impl/mpi/src/dart_synchronization.c
> +    dart__base__mutex_unlock(&lock->mutex);
Return value unchecked

2017-03-17 22:12 UTC, fuchsto commented on dart-impl/mpi/src/dart_synchronization.c
> +  dart__base__mutex_unlock(&lock->mutex);
Return value unchecked

2017-03-17 22:12 UTC, fuchsto commented on dart-impl/mpi/src/dart_synchronization.c
> +  dart__base__mutex_destroy(&(*lock)->mutex);
All return values unchecked in this function

2017-03-19 19:47 UTC, devreal commented
@fuchsto Should all be fixed.

2017-03-19 22:41 UTC, fmoessbauer commented on dart-impl/base/include/dash/dart/base/mutex.h
> +  pthread_mutex_init(&mutex->mutex,
Does this compile? Syntax looks faulty to me.

2017-03-20 22:34 UTC, devreal commented on dart-impl/base/include/dash/dart/base/mutex.h
> +  pthread_mutex_init(&mutex->mutex,
Oh boy, my touchpad tricked me into that. Thanks for spotting this, fixed a bunch of other problems as well.

2017-03-21 11:00 UTC, fuchsto approved these changes

2017-03-27 15:59 UTC, devreal commented
The thread-safety tests fail for strange reasons. I am on it but so far clueless...

2017-03-27 16:38 UTC, fmoessbauer commented
I guess the pointer is not initialized correctly?

```
[    2 ERROR ] [  1959 ] dart_globmem.c           :162  !!! DART: dart_memfree: invalid local global pointer: invalid offset: 0
[    2 ERROR ] [  1959 ] dart_synchronization.c   :374  !!! DART: Failed to free global mmeory
terminate called after throwing an instance of 'dash::exception::AssertionFailed'
  what():  [ Unit 2 ] Assertion 0 == 2 failed: dart_team_lock_free failed /opt/dash/dash/src/Mutex.cc:14
[    1 ERROR ] [  1958 ] dart_globmem.c           :162  !!! DART: dart_memfree: invalid local global pointer: invalid offset: 0
[    1 ERROR ] [  1958 ] dart_synchronization.c   :374  !!! DART: Failed to free global mmeory
```

2017-03-27 17:51 UTC, fmoessbauer commented on dart-impl/mpi/src/dart_synchronization.c
> +    MPI_Recv(NULL, 0, MPI_INT, predecessor, 0, team_data->comm,
This seems to hang, at least in debug builds. Unit 0 waits for itself.
```
[    1 DEBUG ] [ 32334 ] Shared.h                 :86   | Shared.Shared(team,owner) >                  | |- _dart_gptr: dart_gptr_t(<000000|00|0000|0000|0000000000000008>)
[    0 DEBUG ] [ 32333 ] dart_communication.c     :781   DART: dart_put_blocking > finished
[    2 TRACE ] [ 32335 ] dart_segment.c           :168   DART: dart_segment_get_disp() seq_id:1 rel_unitid:2
[    2 TRACE ] [ 32335 ] dart_segment.c           :181   DART: dart_segment_get_disp > disp:94157135832688
[    2 TRACE ] [ 32335 ] dart_segment.c           :168   DART: dart_segment_get_disp() seq_id:1 rel_unitid:2
[    2 TRACE ] [ 32335 ] dart_segment.c           :181   DART: dart_segment_get_disp > disp:94157135832688
[    2 DEBUG ] [ 32335 ] dart_synchronization.c   :206   DART: dart_lock_acquire: waiting for notification from 2 in team 0
[    1 TRACE ] [ 32334 ] dart_segment.c           :168   DART: dart_segment_get_disp() seq_id:1 rel_unitid:1
[    1 TRACE ] [ 32334 ] dart_segment.c           :181   DART: dart_segment_get_disp > disp:94914551350896
[    1 TRACE ] [ 32334 ] dart_segment.c           :168   DART: dart_segment_get_disp() seq_id:1 rel_unitid:1
[    1 TRACE ] [ 32334 ] dart_segment.c           :181   DART: dart_segment_get_disp > disp:94914551350896
[    1 DEBUG ] [ 32334 ] dart_synchronization.c   :206   DART: dart_lock_acquire: waiting for notification from 1 in team 0
[    0 TRACE ] [ 32333 ] dart_segment.c           :168   DART: dart_segment_get_disp() seq_id:1 rel_unitid:0
[    0 TRACE ] [ 32333 ] dart_segment.c           :181   DART: dart_segment_get_disp > disp:94115753625456
[    0 TRACE ] [ 32333 ] dart_segment.c           :168   DART: dart_segment_get_disp() seq_id:1 rel_unitid:0
[    0 TRACE ] [ 32333 ] dart_segment.c           :181   DART: dart_segment_get_disp > disp:94115753625456
[    0 DEBUG ] [ 32333 ] dart_synchronization.c   :206   DART: dart_lock_acquire: waiting for notification from 0 in team 0
```

2017-03-28 08:53 UTC, devreal commented on dart-impl/mpi/src/dart_synchronization.c
> +    MPI_Recv(NULL, 0, MPI_INT, predecessor, 0, team_data->comm,
This is the same that @rkowalewski reported in #339. However, I cannot reproduce this locally. What is your test case? One node? Multi-node? 

I added two test cases to specifically test the `dart_lock` implementation: https://github.com/dash-project/dash/blob/bug-330-dart-lock/dash/test/dart/DARTLockTest.cc

Can you please run this basic test to verify correctness of DART log?

2017-03-28 08:54 UTC, devreal commented
I have fixed an invalid free in `dart_team_lock_destroy`, yes.

2017-03-28 09:17 UTC, fmoessbauer commented on dart-impl/mpi/src/dart_synchronization.c
> +    MPI_Recv(NULL, 0, MPI_INT, predecessor, 0, team_data->comm,
Hi, this output was generated using a debug build, 1 node, 3 units, OpenMPI 1.10.3:
[dart_mutex.txt](https://github.com/dash-project/dash/files/875093/dart_mutex.txt)

2017-03-28 14:47 UTC, devreal commented on dart-impl/mpi/src/dart_synchronization.c
> +    MPI_Recv(NULL, 0, MPI_INT, predecessor, 0, team_data->comm,
OK, so this was a tough one: 

1. The reason this started to fail: I added error checking to the `dart_lock` interface. Sensible thing. 
2. The root cause: `DART_ASSERT_RETURNS` called the `expr` twice, once in the `if` and once in `assert`. Of course, calling `MPI_Fetch_and_op` twice does not yield the same  result on the second call as on the first call. 

I think someone here owes me a beer :)

2017-03-28 15:29 UTC, devreal commented
This might also solve #320. I couldn't reproduce this issue with thread-support enabled, for reasons I have not figured out, yet.

2017-03-28 15:59 UTC, devreal commented
Yep, this should do it: if thread-support is detected, the code in `Threadsupport.cmake` falsely overwrote `CMAKE_C_FLAGS` with `CMAKE_C_FLAGS_RELEASE`, which set `-DNDEBUG` globally and thus disabled the `assert` in the `DART_ASSERT*` macros. Should be all fixed now.

2017-03-28 16:10 UTC, fmoessbauer commented
Great effort!!! That killed several birds with one stone hit.

2017-03-28 21:51 UTC, fuchsto commented
Good stuff as usual, but also close to no unit tests as usual :P
Could you extend them? Hard to believe the additional 100 lines of test cover the changes in this PR.

2017-03-28 21:52 UTC, fuchsto requested changes
@devreal Good stuff as usual, but also close to no unit tests as usual :P
Could you extend them? Hard to believe the additional 100 lines of test cover the changes in this PR.

EDIT: Naah, I owe you one. Will add more tests and merge.

2017-03-29 06:58 UTC, devreal commented
I improved test coverage and adapted the interface a bit, including documentation. Let me know if you can think of any other test that is missing.

2017-03-29 10:06 UTC, fuchsto approved these changes

2017-03-29 10:06 UTC, fuchsto commented
Thank you, that was quick.

2017-03-29 10:06 UTC, merged