Added debug build script
dash-project/dash pull request #332
Opened 2017-03-17 13:32 UTC by ddiefenthaler

With pull request #232 the developer build setting now produce a huge amout of warnings.
There was this comment ([link](https://github.com/dash-project/dash/pull/232#issuecomment-271174182)) in the pull request:

>The "excessive" compiler warnings are only enabled in developer (not debug) build config, so we don't have to fix all of them right now. There just should be a way to make them visible.

This pull request adds a script with default debug build settings, so that the difference between the two build modes is easier to spot.

The script also builds to build.dev as apart from the warnings the actual build result should be similar.

2017-03-17 13:33 UTC, ddiefenthaler commented
@fmoessbauer On the topic of build scripts is there a reason why HDF5 is disabled in the current build.dev script?

2017-03-17 14:18 UTC, fmoessbauer commented
@ddiefenthaler I don't know any, so from my side it's ok to re-enable it.

2017-03-17 22:13 UTC, fuchsto requested changes

2017-03-17 22:13 UTC, fuchsto commented on build.debug.sh
> +                        -DENABLE_THREADSUPPORT=OFF \
Why disable thread support?

2017-03-17 22:31 UTC, ddiefenthaler commented on build.debug.sh
> +                        -DENABLE_THREADSUPPORT=OFF \
No particular reason, I just copied it from the other build scripts,
but I can activate it for them as well.

2017-03-17 22:46 UTC, ddiefenthaler commented on build.debug.sh
> +                        -DENABLE_THREADSUPPORT=OFF \
I enabled thread support for
- build.sh,
- build.dev.sh and
- build.debug.sh

2017-03-18 01:07 UTC, fuchsto approved these changes

2017-03-19 19:50 UTC, devreal approved these changes

2017-03-19 20:30 UTC, ddiefenthaler commented
While looking at the readme I noticed that the table with the build scripts only lists 3 out of the 7 current scripts. Should this list get completed?

The table from the [README.md](https://github.com/dash-project/dash/blob/development/README.md#building-from-source):
>Script file name | Description 
>:--------------- | :-------------------------------------
>`build.sh`       | Standard release build
>`build.dev.sh`   | Development / debug build
>`build.mic.sh`   | Release build for Intel MIC (Xeon Phi)

2017-03-19 21:08 UTC, ddiefenthaler commented
Possible new table:

Script file name | Description 
:--------------- | :-------------------------------------
`build.sh`       | Standard release build
`build.minimal.sh` | Minimal build settings without external libraries and tests
`build.debug.sh`   | Debug build with logging and debug symbols
`build.dev.sh`   | Development / debug build with additional compiler warnings
`build.nasty.sh` | Build and link against a special version of MPI to reveal errors
`build.cov.sh`   | Build script with code coverage of the tests
`build.analyze.sh` | Build script with static code analysis
`build.mic.sh`   | Release build for Intel MIC (Xeon Phi)

Is this too much or would this make sense in a readme file?

2017-03-21 15:36 UTC, BenjaProg commented
Is `build.minimal.sh` supposed to build examples as well?
Currently they are enabled.

2017-03-21 15:52 UTC, fuchsto commented
@BenjaProg Yes, that's fine, the "minimal" refers to optional features, not the number of build targets.

2017-03-21 15:53 UTC, merged