Optimizations in the MPI backend
dash-project/dash pull request #335
Opened 2017-03-21 22:12 UTC by devreal

Reduce the number of MPI calls necessary (reported by @fuerlinger):

1. Cache rank and size in any team and globally.
2. Use `memcpy` on puts and gets if source and target is the same unit.

Also in the MPI backend:
 
3. Use `MPI_Rget` and `MPI_Wait` to decouple `dart_get_blocking` from other non-blocking operations (`dart_put_blocking` still has to call `MPI_Win_flush` to ensure remote completion)

2017-03-22 08:13 UTC, dhinf approved these changes

2017-03-22 15:17 UTC, rkowalewski commented
I think the change in [commit](https://github.com/dash-project/dash/pull/335/commits/3fc32d3b8e565dd1b080c4a8a65dff4812d6009a) are now obsolete after the discussion today since we use now a window per container not per team, right? While semantically it makes not really a difference the standard mentions a [paper](http://dl.acm.org/citation.cfm?id=2798443.2780584) by the RMA Working group mentions that request based operations are generally slower due to the request management in MPI libraries.

But anyway, I understand the point that we need fine-grained completion semantics which are independent from other operations in flight. If it cause some performance related issues we can always roll back to the flush approach.

2017-03-22 15:19 UTC, rkowalewski reviewed
looks good

2017-03-23 15:04 UTC, fuchsto requested changes

2017-03-23 15:04 UTC, fuchsto commented on dart-impl/mpi/src/dart_team_group.c
> +    *size = 0;
Function always returns `OK`.
For example in this line, should return `DART_ERR_OTHER`

2017-03-23 15:04 UTC, fuchsto commented on dart-impl/mpi/src/dart_team_group.c
>      unitid->id = -1;
Should return `DART_ERR_OTHER`

2017-03-23 16:41 UTC, devreal commented on dart-impl/mpi/src/dart_team_group.c
> +    *size = 0;
Fixed.

2017-03-23 21:49 UTC, fuchsto commented on dart-impl/mpi/src/dart_team_group.c
> +    *size = 0;
Same in `dart_myid`

2017-03-23 22:16 UTC, devreal commented on dart-impl/mpi/src/dart_team_group.c
> +    *size = 0;
Fixed there as well, see https://github.com/dash-project/dash/pull/335/commits/e62ddc4dc45f9248f450efd755f2f0afbe89271d

2017-03-23 22:32 UTC, fuchsto commented
@devreal @rkowalewski 

Tests in CI failed for NastyMPI:
~~~
[Nasty-MPI ERROR] (src/nasty_runtime/win_storage.c:113) window is not properly initialized (no nasty id!
~~~

See [build 1676](https://circleci.com/gh/dash-project/dash/1676)

2017-03-24 07:47 UTC, devreal commented
Mhh strange, will look into that.

2017-03-24 18:41 UTC, fuchsto approved these changes

2017-03-24 18:41 UTC, fuchsto commented on dart-impl/mpi/src/dart_communication.c
> +  if (MPI_Wait(&req, MPI_STATUS_IGNORE) != MPI_SUCCESS) {
🥇

2017-03-24 19:13 UTC, fuchsto commented
Don't. I cannot reproduce the error reported by NastyMPI, it did not occur before and has not been observed since. Also, I can't identify any changes related to window initialization, or anything else I could nitpick about for that matter.

2017-03-24 19:40 UTC, fuerlinger commented
:+1:  Looks good, here is the updated report:

[cost-mpi.pdf](https://github.com/dash-project/dash/files/868986/cost-mpi.pdf)

One issue that seems to remain is that `MPI_Type_size` is still executed repeatedly (not cached) in the shared window case (called regular in the report).

2017-03-25 06:11 UTC, fuerlinger commented
Looks good! Here is the new report:

[cost-mpi.pdf](https://github.com/dash-project/dash/files/869778/cost-mpi.pdf)

2017-03-26 19:54 UTC, devreal commented
I removed one of the two calls to `MPI_Win_sync` in `dart_flush_all`. One thing left is the double barrier during deallocation: One happens in the d'tor of `dash::Array` and one happens in the `_deallocate` function of the `SymmetricAllocator`. @rkowalewski already noted that `dart_team_memfree` is not collective although the name suggests it to be. We could add the barrier there (slightly more efficient) before the actual deallocation and remove it from the previously mentioned places. However, `dash::Array` then has no control over the synchronization anymore, not sure if that is relevant when using other allocators.

2017-03-28 10:34 UTC, fuchsto commented
@devreal Fine for me, `dart_team_memfree` is only used in `dash::SymmetricAllocator` as expected.
Also, a non-collective deallocation of collectively allocated memory sounds suspicious to me as units might reference remote memory locations that can be deallocated without publishing the removed memory segment.

For non-collective deallocation I would expect a one-sided or epoch-synchronized memory space, and there is the non-collective (as in: one-sided) `dart_memfree` for that.
That's what I use in `GlobUnitMem` (one-sided, asymmetric) and `GlobHeapMem` (collective, imbalanced).

Are you done with this branch? I'd like to merge the PR.

2017-03-28 11:56 UTC, devreal commented
Please go ahead and merge. We will soon overhaul the memory allocation routines in DART anyway.

2017-03-28 15:41 UTC, merged