Check variadic pattern arguments at compile time
dash-project/dash pull request #356
Opened 2017-04-03 15:51 UTC by devreal

This PR changes `dash::internal::PatternArguments` such that variadic pattern argument integrity is checked at compile-time (except for tile-correctness). It also enables arbitrary mixing of `SizeType`, `Distribution`, and `Team|TeamSpec` arguments, as long as the argument list starts with a `SizeType`. Most notably, it catches mixed usage of `Team` and `TeamSpec`, `Distribution` and `DistributionSpec`, as well as `SizeType` and `SizeSpec` specifications at compile-time. 

My attempt to add some `constexpr` magic (as proposed in #354) failed since this style of parsing does not seem to be possible that way as it would require overloading constructor templates. 

As an addition, this PR also introduces `DASH_ASSERT_ALWAYS`, which always asserts even if assertions are disabled. This is required to ensure pattern validity (replaced plain `assert`).

2017-04-04 02:17 UTC, ddiefenthaler reviewed
Looks good, I'll leave some comments inline

2017-04-04 02:17 UTC, ddiefenthaler commented on dash/include/dash/pattern/internal/PatternArguments.h
> +  template<int argc_size, int argc_dist, int has_team, typename ... Args>
Some documentation would be nice for those parameters.

2017-04-04 02:17 UTC, ddiefenthaler commented on dash/include/dash/pattern/internal/PatternArguments.h
> +    check<argc_size, argc_dist, -1>(std::forward<Args>(args)...);
No Team is set in this case, it was probably broken before as well...

2017-04-04 02:17 UTC, ddiefenthaler commented on dash/include/dash/pattern/internal/PatternArguments.h
> +    check<argc_size, argc_dist, 1>(std::forward<Args>(args)...);
No TeamSpec is created in this case,
as it is dependend on `_distspec` it probably has to go in the final `check()` call.

2017-04-04 02:17 UTC, ddiefenthaler commented on dash/include/dash/pattern/internal/PatternArguments.h
> +  void check(const SizeSpec_t & sizeSpec, Args && ... args) {
Perhaps it makes sense to move this function up,
so that the it is grouped with the function taking individual extents.

2017-04-04 02:17 UTC, ddiefenthaler commented on dash/include/dash/pattern/internal/PatternArguments.h
>    /// parameters specifying the distribution pattern.
This comment seems to be shifted.

2017-04-04 02:17 UTC, ddiefenthaler commented on dash/test/pattern/BlockPatternTest.cc
> +  int size = extent_x * extent_x * extent_z;
This change was probably uninteded, as it is currently breaking the tests.

2017-04-04 02:17 UTC, ddiefenthaler commented on dash/test/pattern/BlockPatternTest.cc
> +  EXPECT_EQ(dash::Team::All().size(), pat_ds_t.num_units());
The wrong patterns are checked in those `EXPECT`s.

2017-04-04 02:17 UTC, ddiefenthaler commented on dash/test/pattern/BlockPatternTest.cc
> +      extent_x, extent_x, extent_z);
Probably the wrong y-extent here, too.

2017-04-04 02:17 UTC, ddiefenthaler commented on dash/include/dash/pattern/internal/PatternArguments.h
> +        "pattern constructor!");
This limitation seems a little bit odd,
but I think this is depended on TeamSpec.

2017-04-04 02:17 UTC, ddiefenthaler commented on dash/include/dash/pattern/internal/PatternArguments.h
> +    check<0, 0, 0>(std::forward<Args>(args)...);
Meanwhile it is probably more a parse than a check.

2017-04-09 11:44 UTC, ddiefenthaler approved these changes
It looks good now and should be ready to merge.

I found one more minor thing that is TeamSpec related,
but I think TeamSpec needs its own issue/pull request, so it shouldn't be important for now.

2017-04-09 11:44 UTC, ddiefenthaler commented on dash/include/dash/pattern/internal/PatternArguments.h
> +    _teamspec = TeamSpec_t(team);
Possibly overwrites previously set TeamSpec.
Should already be handled by check in line [255](https://github.com/dash-project/dash/pull/356/files#diff-703bc11c993d6436737bb7664d6b84a0R255).

2017-04-09 11:44 UTC, ddiefenthaler commented on dash/include/dash/pattern/internal/PatternArguments.h
> +    }
I think it is possible to return without `_team` set, how about:
```c++
if(!ArgcTeam) {
  _team = &dash::Team::All()
}
if(!ArgcTeamSpec) {
  _teamspec = TeamSpec_t(_distspec, *_team);
}
```

I'm not sure about the use cases of this constructor,
so perhaps it is also fine to return without a team.

2017-04-12 16:04 UTC, ddiefenthaler commented on dash/include/dash/pattern/internal/PatternArguments.h
> +      ArgcTeam>(std::forward<Args>(args)...);
Is the use of `ArgcTeam` instead of `ArgcTeamSpec` intended here?

2017-04-12 16:04 UTC, ddiefenthaler commented on dash/include/dash/pattern/internal/PatternArguments.h
> +      ArgcTeam>(std::forward<Args>(args)...);
Here too.

2017-04-12 19:46 UTC, fuchsto requested changes

2017-04-12 19:46 UTC, fuchsto commented on dash/include/dash/pattern/internal/PatternArguments.h
> +public:
Why public?

2017-04-18 08:20 UTC, devreal commented
Thanks for the reviews, they should be addressed.

2017-04-19 07:18 UTC, devreal commented on dash/include/dash/pattern/internal/PatternArguments.h
> +    }
The `dash::Team::All` is used by default if no team has been set, see `team()`. The assumption here is that it only makes sense to overwrite the default `TeamSpec` if a team was set. However, I realized that I am not sure about the relation between `DistSpec` and `TeamSpec` and whether we have to create the latter if the former was explicitely given bu the user. Is it even valid to specify both at the same time? @fuchsto can you shed some light?

2017-05-30 00:34 UTC, fuchsto approved these changes

2017-05-30 01:00 UTC, merged