fixed format warnings in release builds
dash-project/dash pull request #362
Opened 2017-04-20 14:15 UTC by fmoessbauer

Fixes all `-Wformat` warnings in the tests. Someone owns me a beer for that.

2017-04-21 07:18 UTC, devreal requested changes
Thanks a lot, I don't know how often I wanted to start doing that as it bothered me as well. Some small points inline.

2017-04-21 07:18 UTC, devreal commented on dash/test/io/HDF5ArrayTest.cc
> +      LOG_MESSAGE("Team %d: read array", static_cast<int>(myteam.position()));
I suggest using `%lu` instead of the cast.

2017-04-21 07:18 UTC, devreal commented on dash/test/io/HDF5ArrayTest.cc
> +      LOG_MESSAGE("Team %d: array read", static_cast<int>(myteam.position()));
I suggest using `%lu` instead of the cast.

2017-04-21 07:18 UTC, devreal commented on dash/test/io/HDF5ArrayTest.cc
> +      LOG_MESSAGE("Team %d: write array", static_cast<int>(myteam.position()));
I suggest using `%lu` instead of the cast.

2017-04-21 07:18 UTC, devreal commented on dash/test/io/HDF5ArrayTest.cc
> +              static_cast<int>(myteam.position()));
I suggest using `%lu` instead of the cast.

2017-04-21 07:18 UTC, devreal commented on dash/test/algorithm/MaxElementTest.cc
> +              static_cast<int>(num_units), block_size,
I suggest using `%zu` instead of the cast for `num_units`

2017-04-23 10:05 UTC, fmoessbauer commented
@devreal your change requests should all be addressed.

2017-04-24 06:56 UTC, devreal approved these changes

2017-04-24 08:12 UTC, merged