Array: Use correct template type for the index of the operator[]s.
dash-project/dash pull request #383
Opened 2017-05-05 10:55 UTC by bertwesarg

2017-05-05 10:56 UTC, devreal approved these changes

2017-05-05 11:55 UTC, devreal requested changes
On second thought, shouldn't it be `index_type` instead of `size_type`?

2017-05-05 12:07 UTC, bertwesarg commented
@dhinf told me, that `size_type` is the guaranteed unsigned type of `index_type`, thus we should use the `size_type`, as negative indices should be prohibited.

2017-05-08 14:33 UTC, fmoessbauer approved these changes

2017-05-09 20:16 UTC, devreal approved these changes

2017-05-11 11:57 UTC, devreal commented
@bertwesarg Can you please rebase/merge against development, CI should be happy now.

2017-05-11 14:26 UTC, merged