Create TeamSpec in PatternArguments
dash-project/dash pull request #453
Opened 2017-10-24 14:18 UTC by devreal

The variadic pattern arguments parser should create a team-spec that matches the distspec provided by the user, otherwise the pattern is flawed.

2017-10-24 14:34 UTC, devreal commented
OK, I was too fast on this:

```
dash::Matrix<int, 2> mat(size*NX, size*NY, dash::BLOCKED, dash::BLOCKCYCLIC(5));
```
now results in
```
$ aprun -n 4 ./pattern_variants
[    1 ERROR ] [ 45244 ] TeamSpec.h               :170  | dash::exception::InvalidArgument             | [ Unit 1 ] TeamSpec(DistributionSpec, Team) only allows one distributed dimension 
```

@fuchsto How should a teamspec be created to make this work?

2017-10-24 18:40 UTC, ddiefenthaler reviewed
Looks good,

the error does not arrive from this PR, for at least not directly.

You can test this with this call:
`dash::Matrix<int, 2> mat(size*NX, size*NY, dash::BLOCKED, dash::BLOCKCYCLIC(5), dash::Team::All());`
The same error arises.
But it requires your change with the `std::forward`.

I also noticed that `TeamSpec` would need some rework a while ago. But as @fuchsto mentioned a dependency to the topology of the system, I wasn't sure how to accomplish this. I only reworked the function `balance_extents`.

2017-10-25 15:08 UTC, devreal commented
Update: The parser now creates a TeamSpec in the following cases:

1) The DistributionSpec contains only distributions that are not `NONE`; 
2) The DistributionSpec contains only one distribution is not `NONE`.

For 1), we create a balanced teamspec. For 2), a teamspec is created based on the distspec.
This covers all two-dimensional patterns. For three-dimensional patterns, the parser errors out on things like `BLOCKED, BLOCKED, NONE` because I have no clue what a correct TeamSpec looks like. @fuchsto Can we automate this?

2017-10-25 17:10 UTC, ddiefenthaler requested changes

2017-10-25 17:10 UTC, ddiefenthaler commented on dash/test/pattern/VarArgsPatternTest.cc
> +                             dash::BLOCKED, dash::BLOCKCYCLIC(5));
Is the use of `5` instead of `NY` here on purpose?
I see the test break if NY is too low.

2017-10-25 17:10 UTC, ddiefenthaler commented on dash/test/pattern/VarArgsPatternTest.cc
> +                             dash::BLOCKCYCLIC(3), dash::BLOCKCYCLIC(5));
Here too.
Some goes for `3` and `NX`.

2017-10-25 17:10 UTC, ddiefenthaler commented on dash/test/pattern/VarArgsPatternTest.cc
> +                             dash::BLOCKCYCLIC(3), dash::BLOCKCYCLIC(5));
Here too.

2017-10-25 17:10 UTC, ddiefenthaler commented on dash/test/pattern/VarArgsPatternTest.cc
> +                                                 dash::TILE(3), dash::TILE(5));
Here too.

2017-10-26 08:33 UTC, ddiefenthaler approved these changes
Thanks!

Looks good for me.
But the word of @fuchsto is here probably worth more than mine.

2017-11-20 18:16 UTC, merged