Check presence of std::is_trivially_copyable
dash-project/dash pull request #476
Opened 2018-01-08 14:33 UTC by pascalj

Relying on the compiler versions to find out whether std::is_trivially_copyable is present is error-prone. For example clang 5.0 broke because `__GNUC_` is defined.

Instead use cmake to verify that `std::is_trivially_copyable` (and `__has_trivial_copy` as a fallback) is present.

This might be more reasonable than [solving SAT](https://github.com/01org/tbb/blob/4c73c3b5d7f78c40f69e0c04fd4afb9f48add1e6/include/tbb/tbb_config.h) for every new compiler.

2018-01-08 14:35 UTC, pascalj commented on dash/include/dash/Types.h
> +              && __has_trivial_copy(T)
NB: this was an alias in older GCC versions.

2018-01-08 14:39 UTC, rkowalewski commented
Note that this approach does not work if one relies on `make` as the build tool.

2018-01-08 23:17 UTC, devreal requested changes
Looks good, thanks! Just a minor change, see inline.

2018-01-08 23:17 UTC, devreal commented on dash/CMakeLists.txt
> +       ${ADDITIONAL_COMPILE_FLAGS} -DSTD_TRIVIALLY_COPYABLE_AVAIL)
I suggest to use the `DASH_` prefix for macros, i.e., `DASH_HAVE_STD_TRIVIALLY_COPYABLE`, and similar below.

2018-01-08 23:17 UTC, devreal commented on CMakeExt/StdLib.cmake
> +  " HAVE_TRIVIAL_COPY_INTRINSIC)
We could issue a warning if the compiler supports neither

2018-01-08 23:18 UTC, devreal commented
> Note that this approach does not work if one relies on make as the build tool.

@rkowalewski Do you mean the plain makefiles or the Makefiles generated by CMake?

2018-01-09 07:54 UTC, rkowalewski commented
I mean our plain Makefiles. :)

2018-01-09 08:01 UTC, devreal commented
I guess there is a metric ton of features that break when using the plain makefiles. I can't even remember the reason why we still have these Makefiles around...

2018-01-09 12:29 UTC, pascalj commented
Thanks! Switched to `DASH_HAVE_STD_TRIVIALLY_COPYABLE` and added a warning. The check for the intrinsic will now only execute if `std::is_trivially_copyable` is missing.

2018-01-09 12:32 UTC, devreal approved these changes

2018-01-10 00:47 UTC, merged