[WIP] dart Min/Max reduction
dash-project/dash pull request #561
Opened 2018-06-11 13:46 UTC by pascalj

See #548. The benchmark itself will be removed. I ran it on 1 to 8 nodes with constant 32 processes and the results are pretty much what I would expect, although attaching the shared variable seems _really_ expensive.

![1806jn0ro](https://user-images.githubusercontent.com/330168/41235164-6b8f18b6-6d8e-11e8-9934-b36cfed6bbc4.png)

How do we handle things like [this cast](https://github.com/dash-project/dash/compare/development...pascalj:bench-allreduce?expand=1#diff-017a40a28d52a5bca9d048272afceeb5R86)? Macros or should we simply do all this in C++?

2018-06-11 13:53 UTC, devreal commented
Thanks for the measurements. How many iterations did you measure? And did you use shared/dynamic windows? The shared should not involve memory allocation as local allocations are handled through the buddy allocator.

Regarding the types used in `dart__min_max_reduce`: I think we can generate that code with a macro  and establish a register mapping types to operations.

2018-06-11 17:16 UTC, pascalj commented
Sorry, I accidentally pushed from the wrong computer. It should build now.

Here's the benchmark header for the run on 4 nodes:

```
----------------------------------------------------------------------------------
-- Benchmark
--   identifier                                                 bench.13.allreduce
--   date                                                 Mon Jun 11 14:43:21 2018
----------------------------------------------------------------------------------
-- MPI Environment Flags
--   I_MPI_INFO_NUMA_NODE_NUM                                                    2
--   I_MPI_INFO_NUMA_NODE_MAP                                             mlx4_0:0
--   I_MPI_PERHOST                                                        allcores
--   I_MPI_HYDRA_BRANCH_COUNT                                                    4
--   MP_PE_AFFINITY                                                            yes
--   I_MPI_FABRICS                                                        shm:dapl
--   I_MPI_EXTRA_FILESYSTEM                                                    off
--   I_MPI_PLATFORM                                                        uniform
--   MIC_LD_LIBRARY_PATH /lrz/sys/intel/studio2017_u6/compilers_and_libraries_2017.6.256/linux/mkl/lib/mic:/lrz/sys/intel/studio2017_u6/compilers_and_libraries_2017.6.256/linux/compiler/lib/mic
--   I_MPI_JOB_FAST_STARTUP                                                      0
--   MIC_LD_LIBRARY_PATH_modshare /lrz/sys/intel/studio2017_u6/compilers_and_libraries_2017.6.256/linux/compiler/lib/mic:1:/lrz/sys/intel/studio2017_u6/compilers_and_libraries_2017.6.256/linux/mkl/lib/mic:1
--   MP_RFIFO_SIZE                                                        16777216
--   MIC_LIBRARY_PATH /lrz/sys/intel/studio2017_u6/compilers_and_libraries_2017.6.256/linux/mkl/lib/mic:/lrz/sys/intel/studio2017_u6/compilers_and_libraries_2017.6.256/linux/compiler/lib/mic
--   MP_FIFO_MTU                                                              4096
--   MP_BULK_MIN_MSG_SIZE                                                    65536
--   MP_RDMA_MTU                                                                4K
--   MP_RC_MAX_QP                                                             8192
--   I_MPI_ADJUST_GATHER                                                         2
--   MP_TASK_AFFINITY                                                         CORE
--   I_MPI_HYDRA_IFACE                                                         ib0
--   I_MPI_HYDRA_PMI_CONNECT                                              alltoall
--   I_MPI_DAPL_UD_PROVIDER                                       ofa-v2-mlx4_0-1u
--   I_MPI_HYDRA_BOOTSTRAP_EXEC                                      llspawn.stdio
--   KMP_AFFINITY                                   granularity=thread,compact,1,0
--   I_MPI_HYDRA_BOOTSTRAP_AUTOFORK                                              0
--   MIC_LIBRARY_PATH_modshare /lrz/sys/intel/studio2017_u6/compilers_and_libraries_2017.6.256/linux/compiler/lib/mic:1:/lrz/sys/intel/studio2017_u6/compilers_and_libraries_2017.6.256/linux/mkl/lib/mic:1
--   MP_SYNC_QP                                                                YES
--   I_MPI_CHECK_DAPL_PROVIDER_COMPATIBILITY                                     0
--   I_MPI_HYDRA_BOOTSTRAP                                                      ll
--   MP_S_SKIP_PMDEXIT_SLEEP                                                   yes
--   OMP_NUM_THREADS                                                             1
--   MP_USE_BULK_XFER                                                          yes
--   I_MPI_PLATFORM_CHECK                                                        0
--   I_MPI_ROOT                       /lrz/sys/intel/studio2017_u6/impi/2017.4.256
--   I_MPI_HYDRA_UUID                         52530000-15ae-2c18-5d6e-050048270a05
--   I_MPI_PM                                                                hydra
--   I_MPI_INTERNAL_MEM_POLICY                                             default
--   I_MPI_RANK_CMD /home/hpc/pr92fo/ri32gav3/src/dash1/build.dev/dash/bench.13.allreduce.mpi
--   I_MPI_CMD mpiexec -n 32 /home/hpc/pr92fo/ri32gav3/src/dash1/build.dev/dash/bench.13.allreduce.mpi
--   I_MPI_INFO_STATE                                                            0
--   I_MPI_INFO_MODE                                                           775
--   I_MPI_INFO_VEND                                                             1
--   I_MPI_INFO_FLGB                                                             0
--   I_MPI_INFO_FLGC                                                     532603903
--   I_MPI_INFO_FLGD                                                   -1075053569
--   I_MPI_INFO_FLGCEXT                                                          0
--   I_MPI_INFO_FLGDEXT                                                          0
--   I_MPI_INFO_DESC                                                    1342177285
--   I_MPI_INFO_BRAND                                            Intel(R) Xeon(R)
--   I_MPI_INFO_SERIAL                                                  E5-2680 0
--   I_MPI_INFO_C_NAME                                                     Unknown
--   I_MPI_INFO_SIGN                                                        132823
--   I_MPI_INFO_LCPU                                                            32
--   I_MPI_INFO_PACK 0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1
--   I_MPI_INFO_CORE 0,1,2,3,4,5,6,7,0,1,2,3,4,5,6,7,0,1,2,3,4,5,6,7,0,1,2,3,4,5,6,7
--   I_MPI_INFO_THREAD 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
--   I_MPI_INFO_CACHE1 0,1,2,3,4,5,6,7,16,17,18,19,20,21,22,23,0,1,2,3,4,5,6,7,16,17,18,19,20,21,22,23
--   I_MPI_INFO_CACHE2 0,1,2,3,4,5,6,7,16,17,18,19,20,21,22,23,0,1,2,3,4,5,6,7,16,17,18,19,20,21,22,23
--   I_MPI_INFO_CACHE3 0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1
--   I_MPI_INFO_CACHES                                                           3
--   I_MPI_INFO_CACHE_SHARE                                                 2,2,32
--   I_MPI_INFO_CACHE_SIZE                                   32768,262144,20971520
--   I_MPI_INFO_NC                                                              16
--   I_MPI_INFO_NP                                                               2
--   I_MPI_PIN_MAPPING                        8:0 0,1 2,2 4,3 6,4 8,5 10,6 12,7 14
--   I_MPI_PIN_INFO                                                     x0,1,16,17
--   I_MPI_EXT_MPI_CALLS_21340                                      0x2ab6fc03ea50
--   I_MPI_THREAD_LEVEL                                                          3
--   I_MPI_NUMBER_OF_MPI_PROCESSES_PER_NODE                                      8
----------------------------------------------------------------------------------
-- DASH Environment Flags
--   DART_MPI_IMPL                                                        intelmpi
--   DASH_FIFO_MTU_SIZE                                                       4096
--   DASH_RDMA_MTU_SIZE                                                         4K
--   DASH_ENABLE_OPENMP                                                          1
--   DASH_ENABLE_NUMA                                                            1
--   DASH_BULK_MIN_MSG_SIZE                                                  65536
--   DASH_BULK_MIN_MSG_SIZE_BYTES                                            65536
--   DASH_RDMA_MTU_SIZE_BYTES                                                 4096
--   DASH_ENABLE_MPI_SHWIN                                                       1
--   DASH_FIFO_MTU_SIZE_BYTES                                                 4096
--   DASH_ENABLE_LAPACK                                                          1
----------------------------------------------------------------------------------
-- DASH Configuration
--   MPI implementation                                                   intelmpi
--   Host syste [...]

2018-06-12 06:46 UTC, rkowalewski commented
> Regarding the types used in dart__min_max_reduce: I think we can generate that code with a macro and establish a register mapping types to operations.

In principle, I agree since it is runtime stuff. However, is causes a lot of code duplication. Assuming we want to add additional reduction operators in future, it simply doesn't scale. Why not templating the reduction functor in C++ and pass a function pointer to the DART runtime. It even allows reducing non-primitive composed types as defined by their operators. DART can then internally create the `MPI_Op` based on the function pointer.

2018-06-12 06:52 UTC, rkowalewski commented on dart-impl/mpi/include/dash/dart/mpi/dart_communication_priv.h
> +  float *lhs = (float *)lhs_;
I would eliminate these magic numbers and replace them with macro definition. The code then like this:
```c
if (rhs[MIN_IDX] > lhs[MIN_IDX]) {
  rhs[MIN_IDX] = lhs[MIN_IDX];
}
```

2018-06-12 06:53 UTC, rkowalewski requested changes
One minor comment is inline.

2018-06-12 07:03 UTC, devreal commented
Yes, it certainly would be feasible to generate these functions in C++, but: both the basic types and the operations are defined by DART so outsourcing the definition of the underlying reduction function completely breaks this abstraction. We do not have support for custom data types so there is no need to provide custom reduction functions. If we decide to add custom data types we can add an interface to provide custom reduction functions. Both would require some work in the DART backend but it might be worth investigating (as our manual reductions don't seem to scale well). For basic types, however, it should be under the control of DART and code duplication should not be an issue as macros can be used to generate these functions.

2018-06-12 07:25 UTC, devreal commented
Here is what I see on the Cray system with 4x24 units: 

```
   96,  craympi,         dart_allreduce.minmax,  0.00516700
   96,  craympi,            dart_allreduce.min,  0.01086100
   96,  craympi,         dart_allreduce.shared,  0.46138500
```

The numbers reflect what Pascal is seeing, although the difference between `shared` and `min[max]` is not as big.

2018-06-12 15:39 UTC, pascalj commented
Closing in favor of #562

2018-06-12 15:39 UTC, closed without merging