Performance efficiency improvements for dash::sort
dash-project/dash pull request #570
Opened 2018-07-23 08:28 UTC by rkowalewski

This branch has couple of changes to increase efficiency of `dash::sort`.

- Internal functions have been moved to a new header (`internal/Sort-inl.h`)
- There are various const correctness "fixes" to enable more aggressive optimization by the compiler
- Replace 2 collective min / max reductions with a single one as proposed by #562.
- Replace one-sided allreduce with a collective dart reduce.
- Added an all-to-all collective communication in DART since it is needed for efficient data exchange, especially in large-scale use cases. This can be replace with more enhanced versions if #569 is fixed.
- Replace the final local sort with a merge. This drastically increases the performance and may achieve a speedup up to 4 (benchmark results on projekt03) depending on the number of sequences. What we utilize here is the fact that all sequences which have been "received" from other units, are already sorted. We merge these sorted sequences pairwise in a binary tree.

I will provide additional benchmarks results soon.

2018-07-24 12:42 UTC, fmoessbauer reviewed
Most of it looks really good. I noticed only some minor points. See my comments inline.

2018-07-24 12:42 UTC, fmoessbauer commented on dart-impl/mpi/src/dart_communication.c
> +    DART_LOG_ERROR("dart_allreduce ! failed: nelem (%zu) > INT_MAX", nelem);
Can we recover from this? It is also not documented in the interface that there is a limit.

2018-07-24 12:42 UTC, fmoessbauer commented on dash/include/dash/algorithm/Sort.h
> +  dart_alltoall(
Wrap this call as it might be not successful

2018-07-24 12:42 UTC, fmoessbauer commented on dash/include/dash/algorithm/Sort.h
> +    iter_type it_copy =
Uff... that could be worth a comment ;)

2018-07-24 12:42 UTC, fmoessbauer commented on dash/include/dash/algorithm/internal/Sort-inl.h
> +    size_t const val =
Probably add a comment?

2018-07-25 13:13 UTC, rkowalewski commented
Thank you for your good review comments @fmoessbauer. Hopefully everything is addressed now.

2018-07-25 14:07 UTC, devreal requested changes
Looks good to me, just one thing I noticed...

2018-07-25 14:07 UTC, devreal commented on dash/include/dash/algorithm/Sort.h
>    if (valid_partitions.empty()) {
Would `valid_partitions` be empty on all units or would the one unit have one partition? If so are  there any collectives on the path taken by that unit? If so we have a problem because the non-empty unit will deadlock...

2018-07-27 07:52 UTC, rkowalewski commented on dash/include/dash/algorithm/Sort.h
>    if (valid_partitions.empty()) {
`valid_partitions` is always equal on all units. ;) So, all units will take this path if no valid partitions have been found.

2018-07-27 08:02 UTC, devreal approved these changes

2018-08-03 13:22 UTC, fmoessbauer commented
Why didn't we notice the compilation error in our CI?

2018-08-06 06:45 UTC, rkowalewski commented
> Why didn't we notice the compilation error in our CI?
We were wondering about this as well and there is definitely something strange going on. @pascalj is fixing that. ;)

2018-08-28 07:55 UTC, fmoessbauer commented
Is this PR ready to merge?

2018-08-28 07:56 UTC, fmoessbauer approved these changes

2018-09-21 07:31 UTC, rkowalewski commented
Discussed in the F2F. Ready to merge if unit tests have successfully passed.

2018-09-21 12:34 UTC, rkowalewski commented
I am not sure why our codecov often hangs, any ideas @fmoessbauer? It just blocks merging and I do not really prefer the hard "sudo" way to force the merge.

2018-09-21 13:19 UTC, fmoessbauer commented
@rkowalewski: There is a problem with external branches (from forks). 

```
==> Uploading reports
    url: https://codecov.io
    query: branch=pull%2F570&commit=4f710f9976e02e755a229a418cd6018ebc8e1d9b&build=4682&build_url=&name=&tag=&slug=dash-project%2Fdash&service=circleci&flags=&pr=570&job=0
    -> Pinging Codecov
HTTP 400
Commit sha does not match Circle build.
```

2018-09-22 11:39 UTC, rkowalewski commented
Hm OK. Then I am not using my private repository anymore for pull requests.

2018-09-22 11:40 UTC, merged