Delayed Initialization for dash::Shared
dash-project/dash pull request #578
Opened 2018-08-10 14:35 UTC by rkowalewski

Similar to #571 we need delayed initialization for `dash::Shared` as well. There are further improvements:

- Like our other containers we provide now a `local()` interface as a shortcut for the owning unit.
- Replace the internal `shared_ptr` encapsulating the `globmem` instance with a `unique_ptr`. I cannot see any reason for `shared_ptr`. Please correct me if I am wrong.

2018-08-10 14:46 UTC, devreal commented
> Replace the internal `shared_ptr` encapsulating the globmem instance with a `unique_ptr`. I cannot see any reason for shared_ptr. Please correct me if I am wrong.

Is there a specific reason we have `shared_ptr` in the other containers?

2018-08-10 14:50 UTC, fmoessbauer commented
Well, as copying was allowed, the shared pointer was necessary to avoid deallocating the globmem. However I do not know of any location where we used that.

2018-08-10 14:53 UTC, rkowalewski commented
> Well, as copying was allowed, the shared pointer was necessary to avoid deallocating the globmem. However I do not know of any location where we used that.

Exactly. That is why I deleted. It is consistent to our other containers which do not provide copy constructor / assignment either. Such a heavyweight copy should not be hidden, the user can do it explicitly.

> Is there a specific reason we have shared_ptr in the other containers?
Which container still uses that?

2018-08-10 14:55 UTC, rkowalewski commented
I am not really happy to move the std memory header into the dash directory. It should be a separate directory in the root. This means additional install directories in our CMake Build. If you prefer this, I can do that as well.

2018-08-10 15:43 UTC, devreal commented
>> Is there a specific reason we have shared_ptr in the other containers?

>Which container still uses that?

My bad, I misread your description, never mind.

2018-08-24 13:01 UTC, devreal requested changes
One comment, otherwise fine with me :+1:

2018-08-24 13:01 UTC, devreal commented on dash/include/dash/Shared.h
> +   */
Please document that `nullptr` is returned on any other unit.

2018-09-20 11:52 UTC, devreal approved these changes

2018-09-21 06:59 UTC, merged