Add dash::Future::valid
dash-project/dash pull request #603
Opened 2018-11-02 13:16 UTC by devreal

Used to check whether a future has been properly initialized (which may not be the case in a `std::vector<dash::Future>`). This is used in the DASH port of Lulesh.

2018-11-02 13:25 UTC, fmoessbauer requested changes
While this should fix the issue Douglas had, we should use this and add documentation.

2018-11-02 13:25 UTC, fmoessbauer commented on dash/include/dash/Future.h
> +    return (_ready || _get_func != nullptr);
What is the semantic of `_ready`? Is it possible to have `_ready==false` and `_get_func != nullptr`? Please document the semantics and meaning of the private members.
... and the public interface seems to be undocumented too.

2018-11-02 13:26 UTC, fmoessbauer commented
... and a unit test for `valid` is missing as well. Sorry for being pedantic, but missing tests have cause so much trouble in the past.

2018-11-02 13:34 UTC, devreal commented on dash/include/dash/Future.h
> +    return (_ready || _get_func != nullptr);
That is why I start to hate putting up PRs. There is documentation missing everywhere so "just fixing something" really isn't possible... Will add documentation though.

2018-11-03 12:36 UTC, fmoessbauer approved these changes
Thanks for the documentation and the unit test. This looks pretty good now ;)

2018-11-04 13:15 UTC, rkowalewski approved these changes
Fine for me as well

2018-11-04 13:16 UTC, merged

2018-11-05 16:53 UTC, douglaspasqualin commented
Thank you guys. I'll test again.